-------------------------------------------Oracle App Pickup---------------------------------------------------------------
// Oracle App Pickup Test Case 1:
Common.setPlatformName "App Pickup"
Common.setPOSPlatformName "OracleApp"
Common.setTestCaseName "spicysand_pickup"
"DAIWrappers/AppDeliveryAndPickup".launchSeleniumSUT
"DAIWrappers/AppDeliveryAndPickup".triggerSeleniumScript

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSOracle".validateReceipt

(*=================================*)
// Oracle App Pickup Test Case 2:
Common.setPlatformName "App Pickup"
Common.setPOSPlatformName "OracleApp"
Common.setTestCaseName "sideitem_pickup"
"DAIWrappers/AppDeliveryAndPickup".launchSeleniumSUT
"DAIWrappers/AppDeliveryAndPickup".triggerSeleniumScript

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSOracle".validateReceipt

(*=================================*)
// Oracle App Pickup Test Case 3:
Common.setPlatformName "App Pickup"
Common.setPOSPlatformName "OracleApp"
Common.setTestCaseName "popcornshrimp_tenders_pickup"
"DAIWrappers/AppDeliveryAndPickup".launchSeleniumSUT
"DAIWrappers/AppDeliveryAndPickup".triggerSeleniumScript

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSOracle".validateReceipt

-------------------------------------------Oracle App Delivery---------------------------------------------------------------
// Oracle App Delivery Test Case 1:
Common.setPlatformName "App Delivery"
Common.setPOSPlatformName "OracleApp"
Common.setTestCaseName "spicysand_delivery"
"DAIWrappers/AppDeliveryAndPickup".launchSeleniumSUT
"DAIWrappers/AppDeliveryAndPickup".triggerSeleniumScript

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSOracle".validateReceipt

(*=================================*)
// Oracle App Delivery Test Case 2:
Common.setPlatformName "App Pickup"
Common.setPOSPlatformName "OracleApp"
Common.setTestCaseName "sideitem_delivery"
"DAIWrappers/AppDeliveryAndPickup".launchSeleniumSUT
"DAIWrappers/AppDeliveryAndPickup".triggerSeleniumScript

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSOracle".validateReceipt

(*=================================*)
// Oracle App Delivery Test Case 3:
Common.setPlatformName "App Pickup"
Common.setPOSPlatformName "OracleApp"
Common.setTestCaseName "popcornshrimp_tenders_delivery"
"DAIWrappers/AppDeliveryAndPickup".launchSeleniumSUT
"DAIWrappers/AppDeliveryAndPickup".triggerSeleniumScript

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSOracle".validateReceipt


