-------------------------------------------Oracle Kiosk---------------------------------------------------------------
// Oracle Kiosk Test Case 1: 6 Pc Boneless Wings Combo
Common.setPlatformName "Kiosk"
Common.setPOSPlatformName "OracleKiosk"
Common.setTestCaseName "6 Pc Boneless Wings Combo"
"DAIWrappers/Kiosk".launchKioskSUT
"DAIWrappers/Kiosk".startKioskOrder
"DAIWrappers/Kiosk".selectDiningOption
"DAIWrappers/Kiosk".selectMainCourse
"DAIWrappers/Kiosk".selectMealAndSize
"DAIWrappers/Kiosk".selectFlavors
"DAIWrappers/Kiosk".selectSides 
"DAIWrappers/Kiosk".selectDrink
"DAIWrappers/Kiosk".selectBiscuit
"DAIWrappers/Kiosk".viewCart
"DAIWrappers/Kiosk".proceedToTender
"DAIWrappers/Kiosk".enterNameOnOrder "Test"
"DAIWrappers/Kiosk".payAtCounter
"DAIWrappers/Kiosk".completeOrder

//POS Oracle - to complete payment then order will be moved to KDS.
"DAIWrappers/Kiosk".payKioskOrder

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSOracle".validateReceipt


// Oracle Kiosk Test Case 2: 1/4 lb Popcorn Shrimp Combo
Common.setPlatformName "Kiosk"
Common.setPOSPlatformName "OracleKiosk"
Common.setTestCaseName "1/4 lb Popcorn Shrimp Combo"
"DAIWrappers/Kiosk".launchKioskSUT
"DAIWrappers/Kiosk".startKioskOrder
"DAIWrappers/Kiosk".selectDiningOption
"DAIWrappers/Kiosk".selectMainCourse 
"DAIWrappers/Kiosk".selectMealAndSize
"DAIWrappers/Kiosk".selectFlavors
"DAIWrappers/Kiosk".selectSides 
"DAIWrappers/Kiosk".selectDrink
"DAIWrappers/Kiosk".selectBiscuit
"DAIWrappers/Kiosk".viewCart
"DAIWrappers/Kiosk".proceedToTender
"DAIWrappers/Kiosk".enterNameOnOrder "Test"
"DAIWrappers/Kiosk".payAtCounter
"DAIWrappers/Kiosk".completeOrder

// POS Oracle - to complete payment then order will be moved to KDS.
"DAIWrappers/Kiosk".payKioskOrder

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSOracle".validateReceipt


-------------------------------------------Sicom Kiosk---------------------------------------------------------------
// Sicom Kiosk Test Case 1: 6 Pc Boneless Wings Combo
Common.setPlatformName "Kiosk"
Common.setPOSPlatformName "SicomKiosk"
Common.setTestCaseName "6 Pc Boneless Wings Combo"
"DAIWrappers/Kiosk".launchKioskSUT
"DAIWrappers/Kiosk".startKioskOrder
"DAIWrappers/Kiosk".selectDiningOption
"DAIWrappers/Kiosk".selectMainCourse
"DAIWrappers/Kiosk".selectMealAndSize
"DAIWrappers/Kiosk".selectFlavors
"DAIWrappers/Kiosk".selectSides 
"DAIWrappers/Kiosk".selectDrink
"DAIWrappers/Kiosk".selectBiscuit
"DAIWrappers/Kiosk".addToCart
"DAIWrappers/Kiosk".viewCart
"DAIWrappers/Kiosk".proceedToTender
"DAIWrappers/Kiosk".enterNameOnOrder "Test"
"DAIWrappers/Kiosk".payAtCounter
"DAIWrappers/Kiosk".completeOrder

// POS Sicom - to complete payment then order will be moved to KDS.
"DAIWrappers/Kiosk".payKioskOrder

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate receipts
"DAIWrappers/POSSicom".validateSicomReceipt


// Sicom Kiosk Test Case 2: 1/4 lb Popcorn Shrimp Combo
Common.setPlatformName "Kiosk"
Common.setPOSPlatformName "SicomKiosk"
Common.setTestCaseName "1/4 lb Popcorn Shrimp Combo"
"DAIWrappers/Kiosk".launchKioskSUT
"DAIWrappers/Kiosk".startKioskOrder
"DAIWrappers/Kiosk".selectDiningOption
"DAIWrappers/Kiosk".selectMainCourse
"DAIWrappers/Kiosk".selectMealAndSize
"DAIWrappers/Kiosk".selectFlavors
"DAIWrappers/Kiosk".selectSides 
"DAIWrappers/Kiosk".selectDrink
"DAIWrappers/Kiosk".selectBiscuit
"DAIWrappers/Kiosk".addToCart
"DAIWrappers/Kiosk".viewCart
"DAIWrappers/Kiosk".proceedToTender
"DAIWrappers/Kiosk".enterNameOnOrder "Test"
"DAIWrappers/Kiosk".payAtCounter
"DAIWrappers/Kiosk".completeOrder

// POS Sicom - to complete payment then order will be moved to KDS.
"DAIWrappers/Kiosk".payKioskOrder

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate receipts
"DAIWrappers/POSSicom".validateSicomReceipt


-------------------------------------------NCR Kiosk---------------------------------------------------------------
// NCR Kiosk Test Case 1: 6 Pc Boneless Wings Combo
Common.setPlatformName "Kiosk"
Common.setPOSPlatformName "NCRKiosk"
Common.setTestCaseName "6 Pc Boneless Wings Combo"
"DAIWrappers/Kiosk".launchKioskSUT
"DAIWrappers/Kiosk".startKioskOrder
"DAIWrappers/Kiosk".selectDiningOption
"DAIWrappers/Kiosk".selectMainCourse
"DAIWrappers/Kiosk".selectMealAndSize
"DAIWrappers/Kiosk".selectFlavors
"DAIWrappers/Kiosk".selectSides 
"DAIWrappers/Kiosk".selectDrink
"DAIWrappers/Kiosk".selectBiscuit
"DAIWrappers/Kiosk".addToCart
"DAIWrappers/Kiosk".viewCart
"DAIWrappers/Kiosk".proceedToTender
"DAIWrappers/Kiosk".enterNameOnOrder "Test"
"DAIWrappers/Kiosk".payAtCounter
"DAIWrappers/Kiosk".completeOrder

// POS NCR - to complete payment then order will be moved to KDS.
"DAIWrappers/Kiosk".payKioskOrder

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate receipts
"DAIWrappers/POSNCR".validateNCRReceipt


// NCR Kiosk Test Case 2: 1/4 lb Popcorn Shrimp Combo
Common.setPlatformName "Kiosk"
Common.setPOSPlatformName "NCRKiosk"
Common.setTestCaseName "1/4 lb Popcorn Shrimp Combo"
"DAIWrappers/Kiosk".launchKioskSUT
"DAIWrappers/Kiosk".startKioskOrder
"DAIWrappers/Kiosk".selectDiningOption
"DAIWrappers/Kiosk".selectMainCourse
"DAIWrappers/Kiosk".selectMealAndSize
"DAIWrappers/Kiosk".selectFlavors
"DAIWrappers/Kiosk".selectSides 
"DAIWrappers/Kiosk".selectDrink
"DAIWrappers/Kiosk".selectBiscuit
"DAIWrappers/Kiosk".addToCart
"DAIWrappers/Kiosk".viewCart
"DAIWrappers/Kiosk".proceedToTender
"DAIWrappers/Kiosk".enterNameOnOrder "Test"
"DAIWrappers/Kiosk".payAtCounter
"DAIWrappers/Kiosk".completeOrder

// POS NCR - to complete payment then order will be moved to KDS.
"DAIWrappers/Kiosk".payKioskOrder

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate receipts
"DAIWrappers/POSNCR".validateNCRReceipt




