// NCR Test Case 2: Classic Chicken Sandwich Combo (Tested by Engineers)
Common.setPlatformName "POS"
Common.setPOSPlatformName "NCR"
Common.setTestCaseName "Classic Chicken Sandwich Combo"
Common.launchNCRPOS
"DAIWrappers/POSNCR".loginToNCRPOS
"DAIWrappers/POSNCR".selectDiningOption
"DAIWrappers/POSNCR".selectMainCourse
"DAIWrappers/POSNCR".selectMealAndOption
"DAIWrappers/POSNCR".selectFlavors
"DAIWrappers/POSNCR".selectSides 
"DAIWrappers/POSNCR".selectDrink
"DAIWrappers/POSNCR".proceedToTender
"DAIWrappers/POSNCR".exactPayment

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSNCR".validateNCRReceipt

--------------------------------------------------------------------------------------------------------------------

// NCR Test Case 3: Classic Chicken Sandwich Dinner (Tested by Engineers)
Common.setPlatformName "POS"
Common.setPOSPlatformName "NCR"
Common.setTestCaseName "Classic Chicken Sandwich Dinner"
Common.launchNCRPOS
"DAIWrappers/POSNCR".loginToNCRPOS
"DAIWrappers/POSNCR".selectDiningOption
"DAIWrappers/POSNCR".selectMainCourse
"DAIWrappers/POSNCR".selectMealAndOption
"DAIWrappers/POSNCR".selectFlavors
"DAIWrappers/POSNCR".selectSides 
"DAIWrappers/POSNCR".selectDrink
"DAIWrappers/POSNCR".proceedToTender
"DAIWrappers/POSNCR".exactPayment

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSNCR".validateNCRReceipt





(*=================================*)
// NCR Test Case 1: Butterfly Shrimp & Tender Combo
Common.setPlatformName "POS"
Common.setPOSPlatformName "NCR"
Common.setTestCaseName "Butterfly Shrimp & Tender Combo"
Common.launchNCRPOS
"DAIWrappers/POSNCR".loginToNCRPOS
"DAIWrappers/POSNCR".selectDiningOption
"DAIWrappers/POSNCR".selectMainCourse
"DAIWrappers/POSNCR".selectMealAndOption
"DAIWrappers/POSNCR".selectFlavors
"DAIWrappers/POSNCR".selectSides 
"DAIWrappers/POSNCR".selectDrink
"DAIWrappers/POSNCR".proceedToTender
"DAIWrappers/POSNCR".exactPayment

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSNCR".validateNCRReceipt


(*=================================*)
// NCR Test Case 2: Classic Chicken Sandwich Combo
Common.setPlatformName "POS"
Common.setPOSPlatformName "NCR"
Common.setTestCaseName "Classic Chicken Sandwich Combo"
Common.launchNCRPOS
"DAIWrappers/POSNCR".loginToNCRPOS
"DAIWrappers/POSNCR".selectDiningOption
"DAIWrappers/POSNCR".selectMainCourse
"DAIWrappers/POSNCR".selectMealAndOption
"DAIWrappers/POSNCR".selectFlavors
"DAIWrappers/POSNCR".selectSides 
"DAIWrappers/POSNCR".selectDrink
"DAIWrappers/POSNCR".proceedToTender
"DAIWrappers/POSNCR".exactPayment

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSNCR".validateNCRReceipt


(*=================================*)
// NCR Test Case 3: Classic Chicken Sandwich Dinner
Common.setPlatformName "POS"
Common.setPOSPlatformName "NCR"
Common.setTestCaseName "Classic Chicken Sandwich Dinner"
Common.launchNCRPOS
"DAIWrappers/POSNCR".loginToNCRPOS
"DAIWrappers/POSNCR".selectDiningOption
"DAIWrappers/POSNCR".selectMainCourse
"DAIWrappers/POSNCR".selectMealAndOption
"DAIWrappers/POSNCR".selectFlavors
"DAIWrappers/POSNCR".selectSides 
"DAIWrappers/POSNCR".selectDrink
"DAIWrappers/POSNCR".proceedToTender
"DAIWrappers/POSNCR".exactPayment

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSNCR".validateNCRReceipt


(*=================================*)
// NCR Test Case 4: Classic Chicken Sandwich Lg Dinner
Common.setPlatformName "POS"
Common.setPOSPlatformName "NCR"
Common.setTestCaseName "Classic Chicken Sandwich Lg Dinner"
Common.launchNCRPOS
"DAIWrappers/POSNCR".loginToNCRPOS
"DAIWrappers/POSNCR".selectDiningOption
"DAIWrappers/POSNCR".selectMainCourse
"DAIWrappers/POSNCR".selectMealAndOption
"DAIWrappers/POSNCR".selectFlavors
"DAIWrappers/POSNCR".selectSides 
"DAIWrappers/POSNCR".selectDrink
"DAIWrappers/POSNCR".proceedToTender
"DAIWrappers/POSNCR".exactPayment

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSNCR".validateNCRReceipt


(*=================================*)
// NCR Test Case 5: Classic Chicken Sandwich ALC
Common.setPlatformName "POS"
Common.setPOSPlatformName "NCR"
Common.setTestCaseName "Classic Chicken Sandwich ALC"
Common.launchNCRPOS
"DAIWrappers/POSNCR".loginToNCRPOS
"DAIWrappers/POSNCR".selectDiningOption
"DAIWrappers/POSNCR".selectMainCourse
"DAIWrappers/POSNCR".selectMealAndOption
"DAIWrappers/POSNCR".selectFlavors
"DAIWrappers/POSNCR".selectSides 
"DAIWrappers/POSNCR".selectDrink
"DAIWrappers/POSNCR".proceedToTender
"DAIWrappers/POSNCR".exactPayment

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSNCR".validateNCRReceipt


(*=================================*)
// NCR Test Case 6: 12 PC Wings Combo
Common.setPlatformName "POS"
Common.setPOSPlatformName "NCR"
Common.setTestCaseName "12 PC Wings Combo"
Common.launchNCRPOS
"DAIWrappers/POSNCR".loginToNCRPOS
"DAIWrappers/POSNCR".selectDiningOption
"DAIWrappers/POSNCR".selectMainCourse
"DAIWrappers/POSNCR".selectMealAndOption
"DAIWrappers/POSNCR".selectFlavors
"DAIWrappers/POSNCR".selectSides 
"DAIWrappers/POSNCR".selectDrink
"DAIWrappers/POSNCR".proceedToTender
"DAIWrappers/POSNCR".exactPayment

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSNCR".validateNCRReceipt


(*=================================*)
// NCR Test Case 7: 12 PC Wings Lg Combo
Common.setPlatformName "POS"
Common.setPOSPlatformName "NCR"
Common.setTestCaseName "12 PC Wings Lg Combo"
Common.launchNCRPOS
"DAIWrappers/POSNCR".loginToNCRPOS
"DAIWrappers/POSNCR".selectDiningOption
"DAIWrappers/POSNCR".selectMainCourse
"DAIWrappers/POSNCR".selectMealAndOption
"DAIWrappers/POSNCR".selectFlavors
"DAIWrappers/POSNCR".selectSides 
"DAIWrappers/POSNCR".selectDrink
"DAIWrappers/POSNCR".proceedToTender
"DAIWrappers/POSNCR".exactPayment

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSNCR".validateNCRReceipt


(*=================================*)
// NCR Test Case 8: 12 PC Wings ALC
Common.setPlatformName "POS"
Common.setPOSPlatformName "NCR"
Common.setTestCaseName "12 PC Wings ALC"
Common.launchNCRPOS
"DAIWrappers/POSNCR".loginToNCRPOS
"DAIWrappers/POSNCR".selectDiningOption
"DAIWrappers/POSNCR".selectMainCourse
"DAIWrappers/POSNCR".selectMealAndOption
"DAIWrappers/POSNCR".selectFlavors
"DAIWrappers/POSNCR".selectSides 
"DAIWrappers/POSNCR".selectDrink
"DAIWrappers/POSNCR".proceedToTender
"DAIWrappers/POSNCR".exactPayment

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSNCR".validateNCRReceipt


(*=================================*)
// NCR Test Case 9: 4 PC BIC Combo
Common.setPlatformName "POS"
Common.setPOSPlatformName "NCR"
Common.setTestCaseName "4 PC BIC Combo"
Common.launchNCRPOS
"DAIWrappers/POSNCR".loginToNCRPOS
"DAIWrappers/POSNCR".selectDiningOption
"DAIWrappers/POSNCR".selectMainCourse
"DAIWrappers/POSNCR".selectMealAndOption
"DAIWrappers/POSNCR".selectFlavors
"DAIWrappers/POSNCR".selectSides 
"DAIWrappers/POSNCR".selectDrink
"DAIWrappers/POSNCR".proceedToTender
"DAIWrappers/POSNCR".exactPayment

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSNCR".validateNCRReceipt


(*=================================*)
// NCR Test Case 10: 4 PC BIC Dinner
Common.setPlatformName "POS"
Common.setPOSPlatformName "NCR"
Common.setTestCaseName "4 PC BIC Dinner"
Common.launchNCRPOS
"DAIWrappers/POSNCR".loginToNCRPOS
"DAIWrappers/POSNCR".selectDiningOption
"DAIWrappers/POSNCR".selectMainCourse
"DAIWrappers/POSNCR".selectMealAndOption
"DAIWrappers/POSNCR".selectFlavors
"DAIWrappers/POSNCR".selectSides 
"DAIWrappers/POSNCR".selectDrink
"DAIWrappers/POSNCR".proceedToTender
"DAIWrappers/POSNCR".exactPayment

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSNCR".validateNCRReceipt


(*=================================*)
// NCR Test Case 11: 4 PC BIC Lg Combo
Common.setPlatformName "POS"
Common.setPOSPlatformName "NCR"
Common.setTestCaseName "4 PC BIC Lg Combo"
Common.launchNCRPOS
"DAIWrappers/POSNCR".loginToNCRPOS
"DAIWrappers/POSNCR".selectDiningOption
"DAIWrappers/POSNCR".selectMainCourse
"DAIWrappers/POSNCR".selectMealAndOption
"DAIWrappers/POSNCR".selectFlavors
"DAIWrappers/POSNCR".selectSides 
"DAIWrappers/POSNCR".selectDrink
"DAIWrappers/POSNCR".proceedToTender
"DAIWrappers/POSNCR".exactPayment

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSNCR".validateNCRReceipt


(*=================================*)
// NCR Test Case 12: 4 PC BIC ALC
Common.setPlatformName "POS"
Common.setPOSPlatformName "NCR"
Common.setTestCaseName "4 PC BIC ALC"
Common.launchNCRPOS
"DAIWrappers/POSNCR".loginToNCRPOS
"DAIWrappers/POSNCR".selectDiningOption
"DAIWrappers/POSNCR".selectMainCourse
"DAIWrappers/POSNCR".selectMealAndOption
"DAIWrappers/POSNCR".selectFlavors
"DAIWrappers/POSNCR".selectSides 
"DAIWrappers/POSNCR".selectDrink
"DAIWrappers/POSNCR".proceedToTender
"DAIWrappers/POSNCR".exactPayment

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSNCR".validateNCRReceipt


(*=================================*)
// NCR Test Case 13: PLU Lookup
Common.setPlatformName "POS"
Common.setPOSPlatformName "NCR"
Common.setTestCaseName "PLU Lookup"
Common.launchNCRPOS
"DAIWrappers/POSNCR".loginToNCRPOS
"DAIWrappers/POSNCR".selectDiningOption
"DAIWrappers/POSNCR".selectMainCourse
"DAIWrappers/POSNCR".applyCoupon
"DAIWrappers/POSNCR".selectMealAndOption
"DAIWrappers/POSNCR".selectFlavors
"DAIWrappers/POSNCR".selectSides 
"DAIWrappers/POSNCR".selectDrink
"DAIWrappers/POSNCR".proceedToTender
"DAIWrappers/POSNCR".exactPayment

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSNCR".validateNCRReceipt


(*=================================*)
// NCR Test Case 14: X% Off
Common.setPlatformName "POS"
Common.setPOSPlatformName "NCR"
Common.setTestCaseName "X% Off"
Common.launchNCRPOS
"DAIWrappers/POSNCR".loginToNCRPOS
"DAIWrappers/POSNCR".selectDiningOption
"DAIWrappers/POSNCR".selectMainCourse
"DAIWrappers/POSNCR".selectMealAndOption
"DAIWrappers/POSNCR".selectFlavors
"DAIWrappers/POSNCR".selectSides 
"DAIWrappers/POSNCR".selectDrink
"DAIWrappers/POSNCR".applyDiscount
"DAIWrappers/POSNCR".proceedToTender
"DAIWrappers/POSNCR".exactPayment

//KDS
"DAIWrappers/KDS".connectToKDS
"DAIWrappers/KDS".bumpOrderIDOnKDS
"DAIWrappers/KDS".disconnectFromKDS

//Validate Receipts
"DAIWrappers/POSNCR".validateNCRReceipt

