// Oracle Test Case 1: Popcorn Shrimp & Tender
Common.setPlatformName "POS"
Common.setPOSPlatformName "Oracle"
Common.setTestCaseName "Popcorn Shrimp & Tender"
Common.launchOraclePOS
"DAIWrappers/POSOracle".loginToOraclePOS

"DAIWrappers/POSNCR".selectMainCourse
"DAIWrappers/POSNCR".selectMealAndOption
"DAIWrappers/POSNCR".selectFlavors
"DAIWrappers/POSNCR".selectSides 
"DAIWrappers/POSNCR".selectDrink
"DAIWrappers/POSNCR".proceedToTender
"DAIWrappers/POSNCR".exactPayment
Common.disconnectFromNCRPOS

//KDS
"DAIWrappers/KDS".connectToNCRKDS
"DAIWrappers/KDS".bumpOrderIDOnNCRKDS
"DAIWrappers/KDS".disconnectFromNCRKDS

(*=================================*)


