// Oracle Test Case 1: Butterfly Shrimp & Tender Combo
Common.setPlatformName "POS"
Common.setPOSPlatformName "Sicom"
Common.setTestCaseName "12P Wings Large Combo"
Common.launchSicomPOS

"DAIWrappers/POSNCR".selectDiningOption
"DAIWrappers/POSNCR".selectMainCourse
"DAIWrappers/POSNCR".selectMealAndOption
"DAIWrappers/POSNCR".selectFlavors
"DAIWrappers/POSNCR".selectSides 
"DAIWrappers/POSNCR".selectDrink
"DAIWrappers/POSNCR".proceedToTender
"DAIWrappers/POSNCR".exactPayment
Common.disconnectFromNCRPOS

//KDS
"DAIWrappers/KDS".connectToNCRKDS
"DAIWrappers/KDS".bumpOrderIDOnNCRKDS
"DAIWrappers/KDS".disconnectFromNCRKDS

(*=================================*)


